default: &default
  adapter: postgresql
  pool: <%= ENV["DATABASE_POOL"] || 64 %>
  username: <%= ENV["DATABASE_USERNAME"] || 'postgres' %>
  password: <%= ENV["DATABASE_PASSWORD"] || 'postgres' %>
  host: <%= ENV["DATABASE_HOST"] || '127.0.0.1' %>
  timeout: 5000
  encoding: utf-8

development:
  <<: *default
  database: homeland-dev

test:
  <<: *default
  database: homeland-test

production:
  <<: *default
  database: homeland-prod
